default: &default
  adapter: postgresql
  encoding: unicode
<% if ENV.key?('DATABASE_URL') %>
  url: <%= ENV['DATABASE_URL'] %>
<% else %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { nil } %>
<% end %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling

development:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <<: *default
<% unless ENV.key?('DATABASE_URL') %>
  database: lingu_development
<% end %>

test:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <<: *default
<% unless ENV.key?('DATABASE_URL') %>
  database: lingu_test
<% end %>

staging:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  <<: *default
  <% unless ENV.key?('DATABASE_URL') %>
  database: <%= ENV.fetch("DB_NAME") { 'lingu_production' } %>
  <% end %>

production:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  <<: *default
<% unless ENV.key?('DATABASE_URL') %>
  database: <%= ENV.fetch("DB_NAME") { 'lingu_production' } %>
<% end %>
